CREATE OR ALTER VIEW POTS_LIDS
(
 POT_ID,
 POT_NAME,
 POT_DIAMETER,
 POT_VOLUME,
 POT_IMAGE,
 LID_COUNT 
) AS 
SELECT 
  P.ID AS POT_ID,
  P.NAME AS POT_NAME,
  P.DIAMETER AS POT_DIAMETER,
  P.VOLUME AS POT_VOLUME,
  P.IMAGE AS POT_IMAGE,
  (SELECT COUNT(L.ID) FROM LID L WHERE L.DIAMETER = P.DIAMETER) AS LID_COUNT
FROM 
  POT P

;
