/*
  LID
*/
INSERT INTO LID (NAME, DIAMETER, IMAGE) VALUES ('Staub lid', 15.5, NULL);
INSERT INTO LID (NAME, DIAMETER, IMAGE) VALUES ('Tescoma lid', 13, NULL);
INSERT INTO LID (NAME, DIAMETER, IMAGE) VALUES ('Lodge lid', 18, NULL);
INSERT INTO LID (NAME, DIAMETER, IMAGE) VALUES ('Tescoma lif Chef', 18, NULL);
INSERT INTO LID (NAME, DIAMETER, IMAGE) VALUES ('Tescoma lid Deluxe', 15.5, NULL);
INSERT INTO LID (NAME, DIAMETER, IMAGE) VALUES ('Staub lid Deluxe', 18, NULL);

/*
  POT
*/
INSERT INTO POT (NAME, DIAMETER, VOLUME, IMAGE) VALUES ('Tescoma pot', 15.5, 1.5, 'potImage1.png');
INSERT INTO POT (NAME, DIAMETER, VOLUME, IMAGE) VALUES ('Staub pot', 18, 3, 'potImage2.png');
INSERT INTO POT (NAME, DIAMETER, VOLUME, IMAGE) VALUES ('Lodge pot', 13, 2.5, 'potImage3.png');
INSERT INTO POT (NAME, DIAMETER, VOLUME, IMAGE) VALUES ('Ikea pot', 21, 5, NULL);
